/* fatfs_sd_spi.c
 *
 * SPI FatFs disk I/O driver for SD cards on STM32H503RBTx (NUCLEO-H503RB)
 *
 * SD-card wiring (from the CubeMX .ioc) – ensure these match your board:
 *   PB10 – SPI3_SCK
 *   PC2  – SPI3_MISO
 *   PC1  – SPI3_MOSI
 *   PB8  – SDCARD_CS (GPIO output – active low)
 *
 * Implements the glue between FatFs and the HAL SPI driver for blocking
 * transfers (no DMA). Suitable for data-logging at SD speeds.
 *
 * 2025-08-06 – generated by ChatGPT
 */

#include "diskio.h"
#include "ff_gen_drv.h"
#include "main.h"    /* HAL SPI handle and CS pin defined here */
#include <string.h>

/* External SPI handle (CubeMX-generated) */
extern SPI_HandleTypeDef hspi3;

/* Select the SPI instance & chip-select macros */
#define SD_SPI_HANDLE    hspi3
#define CS_LOW()         HAL_GPIO_WritePin(SDCARD_CS_GPIO_Port, SDCARD_CS_Pin, GPIO_PIN_RESET)
#define CS_HIGH()        HAL_GPIO_WritePin(SDCARD_CS_GPIO_Port, SDCARD_CS_Pin, GPIO_PIN_SET)

#define SPI_TIMEOUT      100U  /* ms */

/* Card type flags */
#define CT_MMC    0x01
#define CT_SD1    0x02
#define CT_SD2    0x04
#define CT_SDC    (CT_SD1|CT_SD2)
#define CT_BLOCK  0x08

/* SD commands */
#define CMD0     0
#define CMD1     1
#define CMD8     8
#define CMD9     9
#define CMD10    10
#define CMD12    12
#define CMD16    16
#define CMD17    17
#define CMD18    18
#define CMD23    23
#define CMD24    24
#define CMD25    25
#define CMD55    55
#define CMD58    58
#define ACMD41   (0x80+41)

static volatile DSTATUS Stat = STA_NOINIT;
static uint8_t CardType;

/* Transmit and receive one byte over SPI */
static uint8_t spi_txrx(uint8_t data) {
    uint8_t resp;
    HAL_SPI_TransmitReceive(&SD_SPI_HANDLE, &data, &resp, 1, SPI_TIMEOUT);
    return resp;
}

/* Send dummy clocks */
static void send_dummy_clocks(uint8_t count) {
    CS_HIGH();
    while (count--) {
        spi_txrx(0xFF);
    }
}

/* Wait until card is ready (0xFF) or timeout */
static uint8_t wait_ready(uint32_t timeout_ms) {
    uint32_t start = HAL_GetTick();
    uint8_t val;
    do {
        val = spi_txrx(0xFF);
        if (val == 0xFF) return 1;
    } while ((HAL_GetTick() - start) < timeout_ms);
    return 0;
}

/* Deselect SD card (CS high + dummy clock) */
static void deselect_card(void) {
    CS_HIGH();
    spi_txrx(0xFF);
}

/* Select SD card (CS low) and wait until ready */
static uint8_t select_card(void) {
    CS_LOW();
    spi_txrx(0xFF);
    if (wait_ready(500)) return 1;
    deselect_card();
    return 0;
}

/* Send a command packet to SD card */
static uint8_t send_cmd(uint8_t cmd, uint32_t arg) {
    uint8_t res;
    if (cmd & 0x80) {       /* ACMD<n> is CMD55 followed by cmd&0x7F */
        cmd &= 0x7F;
        res = send_cmd(55, 0);
        if (res > 1) return res;
    }
    if (!select_card()) return 0xFF;
    /* Command token */
    spi_txrx(0x40 | cmd);
    /* Argument */
    spi_txrx((uint8_t)(arg >> 24));
    spi_txrx((uint8_t)(arg >> 16));
    spi_txrx((uint8_t)(arg >> 8));
    spi_txrx((uint8_t)arg);
    /* CRC: only valid for CMD0 and CMD8 */
    uint8_t crc = 0x01;
    if (cmd == CMD0) crc = 0x95;
    if (cmd == CMD8) crc = 0x87;
    spi_txrx(crc);
    /* Wait for response */
    for (int i = 0; i < 10; i++) {
        res = spi_txrx(0xFF);
        if (!(res & 0x80)) break;
    }
    return res;
}

/* Receive a data block from SD */
static int receive_data_block(uint8_t *buff, uint16_t btr) {
    uint8_t token;
    uint32_t start = HAL_GetTick();
    while ((HAL_GetTick() - start) < 200) {
        token = spi_txrx(0xFF);
        if (token != 0xFF) break;
    }
    if (token != 0xFE) return 0;
    /* Read data */
    do {
        *buff++ = spi_txrx(0xFF);
    } while (--btr);
    /* Discard CRC */
    spi_txrx(0xFF);
    spi_txrx(0xFF);
    return 1;
}

/* Transmit a data block to SD */
static int transmit_data_block(const uint8_t *buff, uint8_t token) {
    if (!wait_ready(500)) return 0;
    spi_txrx(token);
    if (token != 0xFD) { /* Single block token */
        for (int i = 0; i < 512; i++) {
            spi_txrx(buff[i]);
        }
        /* CRC (dummy) */
        spi_txrx(0xFF);
        spi_txrx(0xFF);
        /* Check data response */
        uint8_t resp = spi_txrx(0xFF);
        if ((resp & 0x1F) != 0x05) return 0;
    }
    return 1;
}

/*------------------------------------------------------------------------------
  Public functions required by FatFs
------------------------------------------------------------------------------*/

DSTATUS SD_initialize(BYTE drv) {
    (void)drv;
    if (Stat & STA_NODISK) return Stat;
    HAL_Delay(10);
    send_dummy_clocks(10);
    CardType = 0;
    if (send_cmd(CMD0, 0) == 1) {
        /* SDv2? */
        if (send_cmd(CMD8, 0x1AA) == 1) {
            uint8_t ocr[4];
            for (int i = 0; i < 4; i++) ocr[i] = spi_txrx(0xFF);
            if (ocr[2] == 0x01 && ocr[3] == 0xAA) {
                uint32_t start = HAL_GetTick();
                while ((HAL_GetTick() - start) < 1000 && send_cmd(ACMD41, 1UL << 30));
                if ((HAL_GetTick() - start) < 1000 && send_cmd(CMD58, 0) == 0) {
                    for (int i = 0; i < 4; i++) ocr[i] = spi_txrx(0xFF);
                    CardType = (ocr[0] & 0x40) ? (CT_SD2 | CT_BLOCK) : CT_SD2;
                }
            }
        } else {
            /* SDv1 or MMC */
            uint8_t cmd = (send_cmd(ACMD41, 0) <= 1) ? ACMD41 : CMD1;
            uint32_t start = HAL_GetTick();
            while ((HAL_GetTick() - start) < 1000 && send_cmd(cmd, 0));
            if (!((HAL_GetTick() - start) < 1000) || send_cmd(CMD16, 512) != 0) {
                CardType = 0;
            }
        }
    }
    deselect_card();
    if (CardType) Stat &= ~STA_NOINIT;
    return Stat;
}

DSTATUS SD_status(BYTE drv) {
    (void)drv;
    return Stat;
}

DRESULT SD_read(BYTE drv, BYTE *buff, LBA_t sector, UINT count) {
    (void)drv;
    if (!count) return RES_PARERR;
    if (Stat & STA_NOINIT) return RES_NOTRDY;
    if (!(CardType & CT_BLOCK)) sector *= 512;
    if (count == 1) {
        if (send_cmd(CMD17, sector) == 0 && receive_data_block(buff, 512) == 1) count = 0;
    } else {
        if (send_cmd(CMD18, sector) == 0) {
            do {
                if (receive_data_block(buff, 512) == 0) break;
                buff += 512;
            } while (--count);
            send_cmd(CMD12, 0);
        }
    }
    deselect_card();
    return count ? RES_ERROR : RES_OK;
}

#if _USE_WRITE
DRESULT SD_write(BYTE drv, const BYTE *buff, LBA_t sector, UINT count) {
    (void)drv;
    if (!count) return RES_PARERR;
    if (Stat & STA_NOINIT) return RES_NOTRDY;
    if (Stat & STA_PROTECT) return RES_WRPRT;
    if (!(CardType & CT_BLOCK)) sector *= 512;
    if (count == 1) {
        if (send_cmd(CMD24, sector) == 0 && transmit_data_block(buff, 0xFE) == 1) count = 0;
    } else {
        if (send_cmd(ACMD41, 0) <= 1) {}
        if (send_cmd(CMD25, sector) == 0) {
            do {
                if (transmit_data_block(buff, 0xFC) == 0) break;
                buff += 512;
            } while (--count);
            transmit_data_block(0, 0xFD);
        }
    }
    deselect_card();
    return count ? RES_ERROR : RES_OK;
}
#endif

#if _USE_IOCTL
DRESULT SD_ioctl(BYTE drv, BYTE cmd, void *buff) {
    (void)drv;
    DRESULT res = RES_ERROR;
    DWORD *dp = (DWORD*)buff;
    uint8_t csd[16];
    if (Stat & STA_NOINIT) return RES_NOTRDY;
    switch (cmd) {
        case CTRL_SYNC:
            if (select_card()) res = RES_OK;
            break;
        case GET_SECTOR_COUNT:
            if (send_cmd(CMD9, 0) == 0 && receive_data_block(csd, 16) == 1) {
                uint32_t csize = ((uint32_t)(csd[7]) << 16) |
                                 ((uint32_t)(csd[8]) << 8)  |
                                  csd[9];
                *dp = (csize + 1) << 10;
                res = RES_OK;
            }
            break;
        case GET_SECTOR_SIZE:
            *(WORD*)buff = 512;
            res = RES_OK;
            break;
        case GET_BLOCK_SIZE:
            *dp = (CardType & CT_SD2) ? 128 : 1;
            res = RES_OK;
            break;
        default:
            res = RES_PARERR;
    }
    deselect_card();
    return res;
}
#endif

/* Link driver into FatFs */
const Diskio_drvTypeDef SD_Driver = {
    SD_initialize,
    SD_status,
    SD_read,
#if _USE_WRITE
    SD_write,
#endif
#if _USE_IOCTL
    SD_ioctl,
#endif
};
